name: "NetRecon docker image deployment"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'



jobs:
    build_and_publish :
      name: Build and publish image
      runs-on: ubuntu-latest
      env:
        DOCKER_IMAGE_NAME: "net-recon"
      steps:
        - uses: actions/checkout@v3
        - name: Build
          working-directory: ./
          run: |
            current_version=$(echo ${{ github.ref_name }} | sed 's/v^\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/')
            current_short_version=$(echo ${{ github.ref_name }} | sed -E 's/^v([0-9]+)\.([0-9]+)\.[0-9]+$/\1.\2/')
            docker build -t $DOCKER_IMAGE_NAME:latest -t $DOCKER_IMAGE_NAME:$current_version -t $DOCKER_IMAGE_NAME:$current_short_version .
        - name: Login to GitHub Container Registry
          run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdin
        - name: Push Docker image to GitHub Container Registry
          run: |
            current_version=$(echo ${{ github.ref_name }} | sed 's/v^\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/')
            current_short_version=$(echo ${{ github.ref_name }} | sed -E 's/^v([0-9]+)\.([0-9]+)\.[0-9]+$/\1.\2/')
            docker tag $DOCKER_IMAGE_NAME:latest ghcr.io/${{ secrets.USERNAME }}/$DOCKER_IMAGE_NAME:latest
            docker tag $DOCKER_IMAGE_NAME:$current_version ghcr.io/${{ secrets.USERNAME }}/$DOCKER_IMAGE_NAME:$current_version
            docker tag $DOCKER_IMAGE_NAME:$current_short_version ghcr.io/${{ secrets.USERNAME }}/$DOCKER_IMAGE_NAME:$current_short_version
            docker push ghcr.io/${{ secrets.USERNAME }}/$DOCKER_IMAGE_NAME:latest
            docker push ghcr.io/${{ secrets.USERNAME }}/$DOCKER_IMAGE_NAME:$current_version
            docker push ghcr.io/${{ secrets.USERNAME }}/$DOCKER_IMAGE_NAME:$current_short_version